--====================================================
--===================CONSULTA 3=======================
--====================================================
select distinct PERSONA.NOMBRE_PERSONA, ROL.NOMBRE_ROL AS ROL, PELICULA.NOMBRE_PELICULA 
from PERSONA, PELICULA_PERSONA, ROL, PELICULA, CARTELERA
where PERSONA.ID_PERSONA=PELICULA_PERSONA.ID_PERSONA_FK and
ROL.ID_ROL=PELICULA_PERSONA.ID_ROL_FK and
PELICULA.ID_PELICULA=PELICULA_PERSONA.ID_PELICULA_FK and
PELICULA.ID_PELICULA=CARTELERA.ID_PELICULA_CARTELERA and
CARTELERA.FECHA>TO_DATE('17-08-2020','dd-mm-yyyy') and
CARTELERA.FECHA<TO_DATE('30-08-2020','dd-mm-yyyy') and
PERSONA.NOMBRE_PERSONA='Anthony Russo'
;

SELECT *
FROM PERSONA;