alter session set "_ORACLE_SCRIPT"=true;

SELECT * FROM USER_ALL.SALA;

SELECT * FROM USER_ALL.CASA_PRODUCTORA;

SELECT * FROM USER_ALL.GENERO;

SELECT * FROM USER_ALL.PELICULA;

SELECT * FROM USER_ALL.PELICULA_GENERO;

SELECT 
    id_cartelera,
    TO_CHAR (hora_inicio, 'HH24:MI') inicio,
    TO_CHAR (hora_fin, 'HH24:MI') fin,
    fecha,
    TO_CHAR( fecha, 'DAY' )  dia, 
    num_sala_cartelera,
    id_pelicula_cartelera
FROM USER_ALL.CARTELERA; ---PENDIENTE INSERCION

SELECT * FROM USER_ALL.PAIS;

SELECT * FROM USER_ALL.ROL;

SELECT * FROM USER_ALL.PERSONA;

SELECT * FROM USER_ALL.PELICULA_PERSONA;