CREATE OR REPLACE TRIGGER tr_actualiza_factura
AFTER INSERT on USER_ALL.DETALLE_FACTURA
FOR EACH ROW
BEGIN
  UPDATE USER_ALL.FACTURA 
    SET USER_ALL.FACTURA.TOTAL_SIN_IVA=USER_ALL.FACTURA.TOTAL_SIN_IVA+(:NEW.SUBTOTAL-(:NEW.SUBTOTAL*0.12)), 
    USER_ALL.FACTURA.MONTO_IVA=USER_ALL.FACTURA.MONTO_IVA+(:NEW.SUBTOTAL*0.12),
    USER_ALL.FACTURA.TOTAL_FACTURA=USER_ALL.FACTURA.TOTAL_FACTURA+:NEW.SUBTOTAL
    WHERE USER_ALL.FACTURA.ID_FACTURA=:NEW.ID_FACTURA;
END tr_actualiza_factura;
/
